skip_commits:
  files:
    - README.md
configuration: Release
version: 4.8.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
artifacts:
- path: .\**\TabRESTMigrate.exe
